{% set name = "osqp" %}
{% set version = "0.6.2.post5" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  - url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
    sha256: b2fa17aae42a7ed498ec261b33f262bb4b3605e7e8464062159d9fae817f0d61
    patches:
      - setup-win.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - pip
    - mkl-devel {{ mkl }}  # [blas_impl == "mkl"]
    - openblas-devel  # [blas_impl == "openblas"]
    - numpy
    - setuptools_scm
    - qdldl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
    - qdldl
    - future

test:
  imports:
    - osqp
    - osqp.codegen
    - osqp.tests
    - osqppurepy
  requires:
    - pytest
  script: run_test.sh  # [unix]
  script: run_test.bat  # [win]

about:
  home: https://osqp.org/
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.

    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/
  dev_url: http://github.com/oxfordcontrol/osqp-python

extra:
  recipe-maintainers:
    - dougalsutherland
