{% set name = "osqp" %}
{% set version = "0.6.3" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  - url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
    sha256: 03e460e683ec2ce0f839353ddfa3c4c8ffa509ab8cf6a2b2afbb586fa453e180
    patches:
      - patches/0001-win-paradiso-lib.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  script_env:
    - CMAKE_GENERATOR='Visual Studio 16 2019' # [win]
    - CMAKE_GENERATOR='Ninja' # [not win]
    - CMAKE_GENERATOR_PLATFORM='x64' # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja # [not win]
  host:
    - python
    - pip
    - mkl-devel {{ mkl }}  # [blas_impl == "mkl"]
    - openblas-devel  # [blas_impl == "openblas"]
    - numpy
    - setuptools_scm
    - qdldl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
    - qdldl
    - future

test:
  imports:
    - osqp
    - osqp.codegen
    - osqp.tests
    - osqppurepy
  requires:
    - pytest
  script: run_test.sh  # [unix]
  script: run_test.bat  # [win]

about:
  home: https://osqp.org/
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.

    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/
  dev_url: http://github.com/oxfordcontrol/osqp-python

extra:
  recipe-maintainers:
    - dougalsutherland
